apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-project-deployment
  labels:
  name: banking-project
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-project
  template:
    metadata:
      labels:
        app: banking-project
    spec:
      containers:
      - name: banking-project
        image: rajputsonalika571/banking-project:latest
        ports:
        - containerPort: 8085
